# Created using wingetcreate

PackageIdentifier: Kiwix.Wikivoyage
PackageVersion: 1.7.3.0
Installers:
- Platform:
  - Windows.Universal
  MinimumOSVersion: 10.0.10240.0
  Architecture: neutral
  InstallerType: msix
  InstallerUrl: https://github.com/kiwix/kiwix-js-windows/releases/download/v1.7.3-Wikivoyage/KiwixWebAppWikivoyage_1.7.3.0_AnyCPU.appxbundle
  InstallerSha256: 9F617DB2F4C8A7E30E709F2CD0C3522A1366F6C319C3491C8F9253D37E153D21
  SignatureSha256: 637A8F0A92EE8C0CD9DF76CDA5CC162A62A2476A5CFFBB5D71914212790325BB
  PackageFamilyName: Kiwix.WikivoyagebyKiwix_qwjmsdmcnwx12
ManifestType: installer
ManifestVersion: 1.0.0
